name: 编译 Electron 应用

on:
  push:
    branches: [ test ]
    paths:
      - package.json
      - electron-builder.yml
      - vite.config.ts
      - electron.vite.config.ts
      - tsconfig.web.json
      - tsconfig.node.json
      - tsconfig.json
      - LICENSE
      - src/renderer/**
      - src/electron/**
      - .github/workflows/build-electron.yml
  workflow_dispatch:

jobs:
  init:
    name: 初始化环境
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_info.outputs.version }}
      hash: ${{ steps.version_info.outputs.hash }}
    steps:

      # 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
            submodules: recursive
            fetch-depth: 3
      # 初始化一些流程需要的环境变量
      - name: 获取版本信息
        id: version_info
        run: |
            echo version=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT
            echo hash=$(git rev-parse --short=7 HEAD) >> $GITHUB_OUTPUT

  build:
    name: 编译${{ matrix.identifier }}平台
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            identifier: win-x64
          - os: macos-latest
            identifier: mac-arm64
          - os: ubuntu-latest
            identifier: linux-x64
          - os: windows-11-arm
            identifier: win-arm
    needs: init

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: 设置环境变量
        run: |
            echo VITE_HASH=${{ needs.init.outputs.hash }} >> $GITHUB_ENV

      - name: 设置 Nodejs
        uses: actions/setup-node@v4
        with:
            node-version: 20.x

      - name: 缓存依赖
        uses: actions/cache@v4
        with:
            path: |
                ~/.cache/yarn
                .yarn/cache
                ~/.npm
                node_modules
            key: ${{ runner.os }}-${{ github.ref_name }}-electron

      - name: 更新依赖
        run: yarn

      - name: 安装 bsdtar(Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libarchive-tools

      - name: 构建 stapxs-qq-lite-x
        if: matrix.os != 'windows-11-arm'
        run: yarn build:electron --publish=never

      - name: 构建 stapxs-qq-lite-x(win arm)
        if: matrix.os == 'windows-11-arm'
        run: yarn build:electron --publish=never --arm64

      - name: 上传 Pacman 包
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}.pacman
            path: dist_electron/*.pacman

      - name: 上传 AppImage 包
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}.appimage
            path: dist_electron/*.AppImage

      - name: 上传 deb 包(amd64)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-amd64.deb
            path: dist_electron/*_amd64.deb

      - name: 上传 deb 包(arm64)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-arm64.deb
            path: dist_electron/*_arm64.deb

      - name: 上传 unpack 包(linux amd64)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-amd64
            path: dist_electron/linux-unpacked

      - name: 上传 unpack 包(linux arm64)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-arm64
            path: dist_electron/linux-arm64-unpacked

      - name: 上传 exe 包(x64)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-x86.exe
            path: dist_electron/*.exe

      - name: 上传 unpack 包(win)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-x86
            path: dist_electron/win-unpacked

      - name: 上传 exe 包(arm)
        if: matrix.os == 'windows-11-arm'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-arm.exe
            path: dist_electron/*.exe

      - name: 上传 unpack 包(arm)
        if: matrix.os == 'windows-11-arm'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-arm
            path: dist_electron/win-arm64-unpacked

      - name: 上传 dmg 包(amd64)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}.dmg
            path: |
                dist_electron/*.dmg
                !dist_electron/*-arm64.dmg

      - name: 上传 dmg 包(arm64)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ needs.init.outputs.version }}-${{ needs.init.outputs.hash }}-${{ matrix.identifier }}-arm64.dmg
            path: dist_electron/*-arm64.dmg
